// .claude/skills/react-feature-based-frontend/templates/src/features/users/components/UserFormDialog.tsx
import { useEffect, useState } from 'react'
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControlLabel,
  MenuItem,
  Switch,
  TextField,
} from '@mui/material'
import type { CreateUserPayload, User } from '@/features/users/types/user'

const ROLES: User['role'][] = ['admin', 'editor', 'viewer']

const emptyForm: CreateUserPayload = { name: '', email: '', role: 'viewer', active: true }

interface UserFormDialogProps {
  open: boolean
  editingUser: User | null
  onClose: () => void
  onSubmit: (payload: CreateUserPayload) => void
}

export function UserFormDialog({ open, editingUser, onClose, onSubmit }: UserFormDialogProps) {
  const [form, setForm] = useState<CreateUserPayload>(emptyForm)

  useEffect(() => {
    setForm(
      editingUser
        ? {
            name: editingUser.name,
            email: editingUser.email,
            role: editingUser.role,
            active: editingUser.active,
          }
        : emptyForm,
    )
  }, [editingUser, open])

  function handleSubmit() {
    if (!form.name || !form.email) return
    onSubmit(form)
  }

  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle>{editingUser ? 'Editar usuário' : 'Novo usuário'}</DialogTitle>
      <DialogContent className="flex flex-col gap-4 !pt-2">
        <TextField
          label="Nome"
          value={form.name}
          onChange={(e) => setForm({ ...form, name: e.target.value })}
          fullWidth
        />
        <TextField
          label="E-mail"
          type="email"
          value={form.email}
          onChange={(e) => setForm({ ...form, email: e.target.value })}
          fullWidth
        />
        <TextField
          select
          label="Papel"
          value={form.role}
          onChange={(e) => setForm({ ...form, role: e.target.value as User['role'] })}
          fullWidth
        >
          {ROLES.map((role) => (
            <MenuItem key={role} value={role}>
              {role}
            </MenuItem>
          ))}
        </TextField>
        <FormControlLabel
          control={
            <Switch
              checked={form.active}
              onChange={(e) => setForm({ ...form, active: e.target.checked })}
            />
          }
          label="Ativo"
        />
      </DialogContent>
      <DialogActions className="!px-6 !pb-4">
        <Button onClick={onClose}>Cancelar</Button>
        <Button variant="contained" onClick={handleSubmit}>
          Salvar
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// .claude/skills/vue-feature-based-frontend/templates/src/features/users/components/UserFormDialog.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { User } from '@/features/users/types/user'

const props = defineProps<{
  modelValue: boolean
  editingUser?: User | null
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  submit: [payload: Omit<User, 'id'>]
}>()

const form = ref({ name: '', email: '', role: 'viewer' as User['role'], active: true })
const formRef = ref()

watch(
  () => props.editingUser,
  (user) => {
    form.value = user
      ? { name: user.name, email: user.email, role: user.role, active: user.active }
      : { name: '', email: '', role: 'viewer', active: true }
  },
  { immediate: true },
)

async function handleSubmit() {
  const { valid } = await formRef.value.validate()
  if (!valid) return
  emit('submit', { ...form.value })
}
</script>

<template>
  <v-dialog
    :model-value="modelValue"
    max-width="480"
    @update:model-value="(v) => emit('update:modelValue', v)"
  >
    <v-card>
      <v-card-title>{{ editingUser ? 'Editar usuário' : 'Novo usuário' }}</v-card-title>
      <v-card-text>
        <v-form ref="formRef" @submit.prevent="handleSubmit">
          <v-text-field
            v-model="form.name"
            label="Nome"
            :rules="[(v: string) => !!v || 'Obrigatório']"
            class="mb-2"
          />
          <v-text-field
            v-model="form.email"
            label="E-mail"
            type="email"
            :rules="[(v: string) => !!v || 'Obrigatório']"
            class="mb-2"
          />
          <v-select
            v-model="form.role"
            label="Papel"
            :items="['admin', 'editor', 'viewer']"
            class="mb-2"
          />
          <v-switch v-model="form.active" label="Ativo" color="primary" />
        </v-form>
      </v-card-text>
      <v-card-actions class="justify-end px-4 pb-4">
        <v-btn variant="text" @click="emit('update:modelValue', false)">Cancelar</v-btn>
        <v-btn color="primary" @click="handleSubmit">Salvar</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
