// frontend/src/app/layouts/default-layout/default-layout.component.ts
import { Component, inject, signal } from '@angular/core'
import { RouterLink, RouterOutlet, Router } from '@angular/router'
import { MatToolbarModule } from '@angular/material/toolbar'
import { MatSidenavModule } from '@angular/material/sidenav'
import { MatListModule } from '@angular/material/list'
import { MatIconModule } from '@angular/material/icon'
import { MatButtonModule } from '@angular/material/button'

import { AuthStore } from '@app/features/auth/state/auth.store'
import { environment } from '@env/environment'

interface NavItem {
  label: string
  icon: string
  route: string
}

@Component({
  selector: 'app-default-layout',
  standalone: true,
  imports: [
    RouterLink,
    RouterOutlet,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatButtonModule,
  ],
  templateUrl: './default-layout.component.html',
})
export class DefaultLayoutComponent {
  private readonly router = inject(Router)
  readonly authStore = inject(AuthStore)

  readonly appName = environment.appName
  readonly sidenavOpened = signal(true)

  readonly navItems: NavItem[] = [
    { label: 'Início', icon: 'dashboard', route: '/' },
    { label: 'Usuários', icon: 'group', route: '/users' },
    { label: 'Cursos', icon: 'school', route: '/courses' },
  ]

  async logout(): Promise<void> {
    await this.authStore.logout()
    this.router.navigate(['/login'])
  }
}

<mat-toolbar color="primary" class="!fixed top-0 z-10">
  <button mat-icon-button (click)="sidenavOpened.set(!sidenavOpened())">
    <mat-icon>menu</mat-icon>
  </button>
  <span class="ml-2">{{ appName }}</span>
  <span class="flex-1"></span>

  <button
    mat-icon-button
    [matMenuTriggerFor]="langMenu"
    [attr.aria-label]="'language.label' | transloco"
    [title]="'language.label' | transloco"
  >
    <mat-icon>translate</mat-icon>
  </button>
  <mat-menu #langMenu="matMenu">
    @for (lang of languageStore.available; track lang.code) {
      <button mat-menu-item (click)="languageStore.setLang(lang.code)">
        @if (lang.code === languageStore.current()) {
          <mat-icon>check</mat-icon>
        }
        <span>{{ lang.label }}</span>
      </button>
    }
  </mat-menu>

  @if (authStore.user(); as user) {
    <span class="mr-3 hidden text-sm sm:inline">{{ user.name }}</span>
  }
  <button mat-icon-button [title]="'common.logout' | transloco" (click)="logout()">
    <mat-icon>logout</mat-icon>
  </button>
</mat-toolbar>

<mat-sidenav-container class="mt-16 min-h-[calc(100vh-4rem)]">
  <mat-sidenav mode="side" [opened]="sidenavOpened()" class="!w-60">
    <mat-nav-list>
      @for (item of navItems; track item.route) {
        <a mat-list-item [routerLink]="item.route">
          <mat-icon matListItemIcon>{{ item.icon }}</mat-icon>
          <span matListItemTitle>{{ item.label | transloco }}</span>
        </a>
      }
    </mat-nav-list>
  </mat-sidenav>

  <mat-sidenav-content class="bg-slate-50">
    <router-outlet />
  </mat-sidenav-content>
</mat-sidenav-container>

// .claude/skills/react-feature-based-frontend/templates/src/layouts/DefaultLayout.tsx
import { useState } from 'react'
import { Outlet, useNavigate, Link as RouterLink, useLocation } from 'react-router-dom'
import {
  AppBar,
  Box,
  Drawer,
  IconButton,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Toolbar,
  Typography,
} from '@mui/material'
import { Dashboard, Group, Logout, Menu as MenuIcon } from '@mui/icons-material'

import { useAuthStore } from '@/features/auth/store/authStore'

const DRAWER_WIDTH = 240

const navItems = [
  { label: 'Início', icon: <Dashboard />, to: '/' },
  { label: 'Usuários', icon: <Group />, to: '/users' },
]

export function DefaultLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useAuthStore((state) => state.user)
  const logout = useAuthStore((state) => state.logout)
  const [drawerOpen, setDrawerOpen] = useState(true)

  async function handleLogout() {
    await logout()
    navigate('/login')
  }

  return (
    <Box className="flex">
      <AppBar
        position="fixed"
        className="!z-10"
        sx={{ width: '100%' }}
      >
        <Toolbar>
          <IconButton
            color="inherit"
            edge="start"
            onClick={() => setDrawerOpen((v) => !v)}
            className="!mr-2"
          >
            <MenuIcon />
          </IconButton>
          <Typography variant="h6" className="flex-1">
            {import.meta.env.VITE_APP_NAME ?? 'App'}
          </Typography>
          {user && (
            <Typography variant="body2" className="mr-3 hidden sm:inline">
              {user.name}
            </Typography>
          )}
          <IconButton color="inherit" title="Sair" onClick={handleLogout}>
            <Logout />
          </IconButton>
        </Toolbar>
      </AppBar>

      <Drawer
        variant="persistent"
        open={drawerOpen}
        sx={{
          width: drawerOpen ? DRAWER_WIDTH : 0,
          flexShrink: 0,
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
      >
        <Toolbar />
        <List>
          {navItems.map((item) => (
            <ListItemButton
              key={item.to}
              component={RouterLink}
              to={item.to}
              selected={location.pathname === item.to}
            >
              <ListItemIcon>{item.icon}</ListItemIcon>
              <ListItemText primary={item.label} />
            </ListItemButton>
          ))}
        </List>
      </Drawer>

      <Box component="main" className="min-h-screen flex-1 bg-slate-50">
        <Toolbar />
        <Outlet />
      </Box>
    </Box>
  )
}
