// .claude/skills/react-feature-based-frontend/templates/src/layouts/AuthLayout.tsx
import { Outlet } from 'react-router-dom'

// Layout minimalista para páginas públicas (login, registro, recuperar senha).
// Sem AppBar/Drawer: só centraliza o conteúdo na tela.
export function AuthLayout() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Outlet />
    </div>
  )
}

// frontend/src/app/layouts/auth-layout/auth-layout.component.ts
import { Component } from '@angular/core'
import { RouterOutlet } from '@angular/router'

// Layout minimalista para páginas públicas (login, registro, recuperar senha).
// Sem toolbar/sidenav: só centraliza o conteúdo na tela.
@Component({
  selector: 'app-auth-layout',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <div class="min-h-screen bg-slate-50">
      <router-outlet />
    </div>
  `,
})
export class AuthLayoutComponent {}
